Feature/refactor anthony
thoth-tech/arcade-machine pull request #34
Opened 2022-07-21 07:55 UTC by studioant

### Refactor T1 code
Applied refactoring to multiple classes to provide greater uniformity

2022-07-22 03:38 UTC, studioant commented
Looks like some conflicts have occurred after previous merge. I will resolve these shortly

2022-07-24 22:58 UTC, studioant commented
@Delcari, merge conflicts resolved, ready for re-review

2022-07-25 03:49 UTC, Delcari requested changes
Seems you reverted a number of changes I had just merged into the main branch from Feature/refactor #30.
I think it'd be wise to revert the last commit and try again! 😞 
I'm happy to perform the merge/resolve conflicts if needed, cheers.

2022-07-25 06:32 UTC, studioant commented
ah, I neglected to commit the merged copy. should be ok now

2022-07-26 07:40 UTC, Delcari commented on Helper.h
> +        {
Still some changes that have been removed it seems? Haven't had a look over all the changes but this function has been affected 😢

2022-07-27 06:28 UTC, lachfoy reviewed
I'm not sure I understand the triple forward slash (///) for some comments, but otherwise everything looks good!

2022-07-27 06:59 UTC, studioant commented
> I'm not sure I understand the triple forward slash (///) for some comments, but otherwise everything looks good!

/// indicates a short description that will be added to the Doxygen documentation. // will not add anything to Doxygen documentation.

2022-07-27 08:20 UTC, Delcari approved these changes
Just glossed over it again, all clear 😄..
Merge whenever ☑️

Probably may as well rename the other classes here too
### EG.
```'gridlayout.h' -> GridLayout.h'```

2022-07-27 13:25 UTC, merged